# validate this config, set false to actually produce zarr files
dry_run: true

# print out log - 0 1 2
verbosity: 2

# inputs
input:
  paths: ./inputs/gridded/2020/*.nc
  sort_by: path # set to name individual files instead of the whole path
  # select variables from netcdf
  variables:
    - dt_analysis
    - sea_surface_temperature
    - l2p_flags
    - sses_bias
    - lat
    - sses_count
    - lon
    - sses_standard_deviation
    - quality_level
#    - sst_dtime
    - satellite_zenith_angle
    - time
#    - sea_ice_fraction
#    - wind_speed
#    - sea_ice_fraction_dtime_from_sst
#    - wind_speed_dtime_from_sst
  # read input files as single block
  multi_file: true
  # concat dimension
  concat_dim: "time"
  # xarray engine
  engine: "netcdf4"
  # turn this on for very large inputs -> force using Dask array, avoid memory issues
  prefetch_chunks: true

# Configuration of input to output processing
process:
  rechunk:
    "*":
      lat: 64
      lon: 64
      time: 64
    lat: null
    lon: null
    time: "input"

# Configuration of output
output:
  path: ./outputs/gridded/2020/test/test_config_gridded.zarr
  consolidated: true
  overwrite: true

