# This configuration file only contains parameters unique to
# OCEANCOLOUR_ATL_CHL_L4_NRT_OBSERVATIONS_009_037 .
# Common parameters are configured in a separate file.

input:
  paths: /eodata/CMEMS/NRT/ATL/CHL/OCEANCOLOUR_ATL_CHL_L4_NRT_OBSERVATIONS_009_037/*/*/*/*_d-*-DT*.nc

process:
  rechunk:
    '*':
      lon: 354
      lat: 276
      time: 5
    lon: null
    lat: null
    time: 10000

output:
  path: s3://cop-services/OCEANCOLOUR_ATL_CHL_L4_NRT_OBSERVATIONS_009_037.zarr/
