# This configuration file only contains parameters unique to
# OCEANCOLOUR_ATL_CHL_L4_NRT_OBSERVATIONS_009_037 .
# Common parameters are configured in a separate file.

input:
  paths: /eodata/CMEMS/NRT/ATL/CHL/OCEANCOLOUR_ATL_CHL_L4_NRT_OBSERVATIONS_009_037/*/*/*/*_d-*-DT*.nc
  # decode_cf: true is a temporary workaround for
  # https://github.com/pydata/xarray/issues/5405
  # (manifesting in nc2zarr as https://github.com/bcdev/nc2zarr/issues/35 ),
  # which affects the conversion of the CHL_error variable. (Unfortunately the
  # nc2zarr workaround in https://github.com/bcdev/nc2zarr/pull/36 doesn't
  # help in this case.)
  decode_cf: true

process:
  rechunk:
    '*':
      lon: 354
      lat: 276
      time: 5
    lon: null
    lat: null
    time: 10000

output:
  path: s3://cop-services/OCEANCOLOUR_ATL_CHL_L4_NRT_OBSERVATIONS_009_037.zarr/
