input:
  paths: /eodata/CMEMS/NRT/MED/CHL/OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041/*/*/*/*_d-*-DT-*.nc
  sort_by: path
  prefetch_chunks: true

process:
  rechunk:
    "*":
      lon: 662
      lat: 320
      time: 5
    time: 365
    lat: null
    lon: null
  
output:
  path: /home/eouser/data/OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041.zarr/
  overwrite: true
  consolidated: true
