# This configuration file only contains parameters unique to
# OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045 .
# Common parameters are configured in a separate file.

input:
  paths:
    - /eodata/CMEMS/NRT/BLA/CHL/OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045/*/*/*/*_d-OC_CNR-L4-CHL-INTERP_MULTI_1KM-BS-DT-v02.nc

process:
  rechunk:
    "*":
      lon: 221
      lat: 158
      time: 25
    time: 365
    lat: null
    lon: null
  
output:
  path: s3://cop-services/OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045.zarr/
