# This configuration file only contains parameters unique to
# OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041 .
# Common parameters are configured in a separate file.

input:
  paths: /eodata/CMEMS/NRT/MED/CHL/OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041/*/*/*/*_d-*-DT-*.nc

process:
  rechunk:
    "*":
      lon: 662
      lat: 320
      time: 5
    time: 365
    lat: null
    lon: null
  
output:
  path: s3://cop-services/OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041.zarr/
