input:
  paths:
    - /eodata/CMEMS/NRT/BLA/CHL/OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045/*/*/*/*_d-OC_CNR-L4-CHL-INTERP_MULTI_1KM-BS-DT-v02.nc
  sort_by: path
  prefetch_chunks: true

process:
  rechunk:
    "*":
      lon: 221
      lat: 158
      time: 25
    time: 365
    lat: null
    lon: null
  
output:
  path: /home/eouser/data/OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045.zarr/
  overwrite: true
  consolidated: true
