input:
  paths:
    - /eodata/CMEMS/NRT/BAL/CHL/OCEANCOLOUR_BAL_CHL_L3_NRT_OBSERVATIONS_009_049/*/*/*/*_d-OC_CNR-L3-CHL-ONNS_Oa_1KM-BAL-DT-v02.nc
  sort_by: path
  prefetch_chunks: true

process:
  rechunk:
    "*":
      lon: 237
      lat: 230
      time: 50
    time: 365
    lat: null
    lon: null
  
output:
  path: /home/eouser/data/OCEANCOLOUR_BAL_CHL_L3_NRT_OBSERVATIONS_009_049.zarr/
  overwrite: true
  consolidated: true
